### ISSUE TITLE
run project locally fails

### ISSUE THREAD

**Issue by olegshilov** [zenorocha/browser-diet#279]
Hi. I would like to translate this project on russian, but can't run it.

![screen shot 2015-10-27 at 03 54 28](https://cloud.githubusercontent.com/assets/930121/10746792/83072d8a-7c5f-11e5-8b8d-a82a51893f85.png)

What i'm doing wrong?

**Comment by zenorocha** [comment]
Hey @olegshilov,

We're still running on a older version of Node (0.10).

**Comment by mkautzmann** [comment]
We could update `docpad` and support v4, what do you think @zenorocha?

**Comment by zenorocha** [comment]
That would be awesome! Could you send a PR?

**Comment by mkautzmann** [comment]
OK, working on it!

**Comment by mkautzmann** [comment]
OK, it's working locally but I had to make a major change as docpad changed a bit: The **assets** are no longer on the `en` folder.

Is that OK or the `en` folder is necessary? I think as long as the assets don't change with the language there is no reason for them to be inside an `en` folder.

If it's necessary I can make they go there but then I have to make a `en` folder inside the `src/document` folder with the assets so that `docpad` maps to the correct place.

Which path should I take?

**Comment by zenorocha** [comment]
It's alright. Assets can be a separate folder.

**Comment by zenorocha** [comment]
Looking forward for this PR!!! Thanks a lot @mkautzmann

**Comment by zenorocha** [comment]
It's working now @olegshilov, a Russian version would be awesome!

**Comment by olegshilov** [comment]
@zenorocha @mkautzmann thanks lot. You can expect PR soon.
